-- MySQL Script generated by MySQL Workbench
-- Mon Nov 14 21:04:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monitor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monitor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monitor` DEFAULT CHARACTER SET utf8 ;
USE `monitor` ;

-- -----------------------------------------------------
-- Table `monitor`.`instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitor`.`instance` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` TINYINT UNSIGNED NOT NULL,
  `fail_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `url` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_instance_service_idx` (`service_id` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  CONSTRAINT `fk_instance_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `monitor`.`service` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `monitor`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitor`.`service` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(45) NOT NULL,
  `enabled` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `instance_id` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_instance1_idx` (`instance_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_instance1`
    FOREIGN KEY (`instance_id`)
    REFERENCES `monitor`.`instance` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `monitor`.`service`
-- -----------------------------------------------------
START TRANSACTION;
USE `monitor`;
INSERT INTO `monitor`.`service` (`id`, `service`, `enabled`, `instance_id`) VALUES (1, 'auth', 1, NULL);
INSERT INTO `monitor`.`service` (`id`, `service`, `enabled`, `instance_id`) VALUES (2, 'queries', 1, NULL);
INSERT INTO `monitor`.`service` (`id`, `service`, `enabled`, `instance_id`) VALUES (3, 'balance', 1, NULL);
INSERT INTO `monitor`.`service` (`id`, `service`, `enabled`, `instance_id`) VALUES (4, 'payment', 1, NULL);

COMMIT;

